CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL IDENTITY , 
	[Name] VARCHAR(100) NOT NULL,
	[Email] VARCHAR (200) UNIQUE NOT NULL,
	[Password] VARCHAR(250) NOT NULL,
	[Role] VARCHAR(20) NOT NULL,
    CONSTRAINT [PK_User] PRIMARY KEY ([Id]) 
)
